### ISSUE TITLE
TestFreeze `make test` failed and frozen

### ISSUE THREAD

**Issue by haiyanmeng** [hmeng-19/runc#2]
I tried to run `make test` and failed.

Here is the configuration of my machine:

```
[hmeng@localhost ~]$ uname -a
Linux localhost.localdomain 4.5.5-201.fc23.x86_64 #1 SMP Sat May 21 15:29:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[hmeng@localhost runc]$ cat /etc/fedora-release
Fedora release 23 (Twenty Three)

[hmeng@localhost ~]$ go version
go version go1.6.2 linux/amd64

[hmeng@localhost ~]$ cd go/src/github.com/opencontainers/runc/
[hmeng@localhost runc]$ git branch
* master
[hmeng@localhost runc]$ git log
commit eb217f273125d3e4d6731389fe804e46e0b14ac6
Merge: e34cb45 ec1ccb9
Author: Mrunal Patel <mrunal@me.com>
Date:   Wed Jun 8 11:45:26 2016 -0700

[hmeng@localhost ~]$ docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-9.gitee06d03.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      ee06d03/1.9.1
 Built:        
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-9.gitee06d03.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      ee06d03/1.9.1
 Built:        
 OS/Arch:         linux/amd64
```

Here is the error of running `make localunittest`. The `TestFreeze` broke and the docker container running the test also frozen.

```
=== RUN   TestFreeze
panic: test timed out after 3m0s


goroutine 16 [running]:
panic(0x721200, 0xc820398a10)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
testing.startAlarm.func1()
    /usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
    /usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 2 minutes]:
testing.RunTests(0x8dcba8, 0xc15460, 0x2f, 0x2f, 0x1)
    /usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820035f08, 0x1)
    /usr/local/go/src/testing/testing.go:515 +0x81
_/go/src/github.com/opencontainers/runc/libcontainer/integration.TestMain(0xc820035f08)
    /go/src/github.com/opencontainers/runc/libcontainer/integration/init_test.go:58 +0x3d7
main.main()
    _/go/src/github.com/opencontainers/runc/libcontainer/integration/_test/_testmain.go:144 +0x114

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
    /usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 101 [runnable]:
time.Sleep(0xf4240)
    /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/opencontainers/runc/libcontainer/cgroups/fs.(*FreezerGroup).Set(0xc43748, 0xc82036ac30, 0x27, 0xc820384050, 0x0, 0x0)
    /home/hmeng/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/cgroups/fs/freezer.go:44 +0x289
github.com/opencontainers/runc/libcontainer/cgroups/fs.(*Manager).Freeze(0xc820396040, 0x829348, 0x6, 0x0, 0x0)
    /home/hmeng/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go:235 +0x207
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Pause(0xc82014a000, 0x0, 0x0)
    /home/hmeng/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/container_linux.go:402 +0x139
_/go/src/github.com/opencontainers/runc/libcontainer/integration.testFreeze(0xc8204ff5f0, 0xc8118fa400)
    /go/src/github.com/opencontainers/runc/libcontainer/integration/exec_test.go:516 +0x600
_/go/src/github.com/opencontainers/runc/libcontainer/integration.TestFreeze(0xc8204ff5f0)
    /go/src/github.com/opencontainers/runc/libcontainer/integration/exec_test.go:470 +0x26
testing.tRunner(0xc8204ff5f0, 0xc15598)
    /usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
    /usr/local/go/src/testing/testing.go:582 +0x892
FAIL    _/go/src/github.com/opencontainers/runc/libcontainer/integration    180.013s
```

**Comment by haiyanmeng** [comment]
@mrunalp , let me know whether `make test` works for you.

**Comment by mrunalp** [comment]
@hmeng-19 I see the same issue. We need to debug this.

**Comment by mrunalp** [comment]
@hmeng-19 The create-start changes broke TestFreeze. It works before that PR.

**Comment by haiyanmeng** [comment]
@mrunalp , I met the same errors:

```
Two tests are failing
    1. TestFreeze hangs
    2. test 26 in bats
```

**Comment by haiyanmeng** [comment]
Just to keep a record, here is the failure from test 26 in bats. 

```
$ docker run -e TESTFLAGS -t --privileged --rm -v /home/hmeng/go/src/github.com/hmeng-19/runc:/go/src/github.com/opencontainers/runc runc_test make localintegration
go build -i -ldflags "-X main.gitCommit=95b5f3b2990f8267f428e771e4bda39bd4ea6676 -X main.version=1.0.0-rc1" -tags "seccomp" -o runc .
....
not ok 26 spec validator
# (in test file tests/integration/spec.bats, line 75)
#   `[ -e src/runtime-spec/schema/schema.json ]' failed
....
```

**Comment by mrunalp** [comment]
The bats test was broken by 
https://github.com/opencontainers/runtime-spec/pull/481/files

**Comment by haiyanmeng** [comment]
It seems that `schema.json` has been renamed to `config-schema.json`. 
The fixes should be referring to the new file names in `tests/integration/spec.bats`.

**Comment by mrunalp** [comment]
Better fix is to use the version that we vendor in runc. I have created a runc PR for that.

**Comment by mrunalp** [comment]
https://github.com/opencontainers/runc/pull/900

**Comment by haiyanmeng** [comment]
@mrunalp , it is pretty cool. Thanks.

Just a quick question, how often the maintainer of `runc` executes `godep update` or any other command which may change `Godeps.json`?

**Comment by mrunalp** [comment]
Whenever we want to update a dependency for new features or bug fixes. We regularly update the runtime-spec dependency.

**Comment by mrunalp** [comment]
https://github.com/opencontainers/runc/pull/901 fixes the TestFreeze issue

**Comment by haiyanmeng** [comment]
Thanks.

**Comment by haiyanmeng** [comment]
@rhatdan, this is the issue Mrunal and me worked on yesterday. 
Mrunal already created two PRs to the upstream.
One PR already got merged. Another PR is still waiting.
